// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAENkk5YTc8c9FiYTcsa7i-KamKYvL_LyE',
    appId: '1:128679673982:web:9f35f3b47ab70a8335982f',
    messagingSenderId: '128679673982',
    projectId: 'prakflutterfirebase-70d5a',
    authDomain: 'prakflutterfirebase-70d5a.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-70d5a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyhLmu8tVbP8Bo8lEgCCtQTC_Xd3DvUyE',
    appId: '1:128679673982:android:258e01d8feee4bbe35982f',
    messagingSenderId: '128679673982',
    projectId: 'prakflutterfirebase-70d5a',
    storageBucket: 'prakflutterfirebase-70d5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCId9aWOlJXNaEVn7EzGMV-AzDzZ3XVWs0',
    appId: '1:128679673982:ios:4ab8567d00daab3235982f',
    messagingSenderId: '128679673982',
    projectId: 'prakflutterfirebase-70d5a',
    storageBucket: 'prakflutterfirebase-70d5a.appspot.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCId9aWOlJXNaEVn7EzGMV-AzDzZ3XVWs0',
    appId: '1:128679673982:ios:4ab8567d00daab3235982f',
    messagingSenderId: '128679673982',
    projectId: 'prakflutterfirebase-70d5a',
    storageBucket: 'prakflutterfirebase-70d5a.appspot.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAENkk5YTc8c9FiYTcsa7i-KamKYvL_LyE',
    appId: '1:128679673982:web:ddca0b924a30661235982f',
    messagingSenderId: '128679673982',
    projectId: 'prakflutterfirebase-70d5a',
    authDomain: 'prakflutterfirebase-70d5a.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-70d5a.appspot.com',
  );
}
